name: project
description: A simple and powerful Todo Task Manager App built using Flutter.

publish_to: 'none' # Prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  lottie: ^3.0.0 # ✅ Lottie added for animation splash

  # Firebase (Optional – only needed if using login)
  # firebase_core: ^2.30.0
  # firebase_auth: ^4.15.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/todo.jpg
    - assets/animations/splash.json
